### ISSUE TITLE
Make cancel selection after gc default behaviour

### ISSUE THREAD

**Issue by Maswor** [b3nj5m1n/kommentary#49] opened 2021-06-17 09:39 UTC
First of all, thank you **b3nj5m1n** for making this awesome plugins

I have this issues, where kommentary differ from commentary from TPop.

1.  Select a text
2. Type _gc_
3. kommentary still keeps the selection, instead of canceling it

I want to ask how I could config Kommentary to emulate commentary behavior, thank you!

**Comment by b3nj5m1n** [comment] 2021-06-18 15:17
Duplicate of #20. Since multiple people have asked about this, we should maybe consider making this a configurable option.

**Comment by b3nj5m1n** [comment] 2021-07-27 10:03
Implemented in fe01018a490813a8d89c09947a7ca23fc0e9e728.

**Closed by b3nj5m1n** 2021-07-27 10:03 UTC
Labels: duplicate, enhancement
