### ISSUE TITLE
Align visually selected single line comments (or option to do so)

### ISSUE THREAD

**Issue by DanCardin** [b3nj5m1n/kommentary#13] opened 2021-02-03 14:41 UTC
Random block of vim config, visually selected (although this also happens for `gc5j`):
```
    smart_rename = {
      enable = true,
      keymaps = {
        smart_rename = "grr"          -- mapping to rename reference under cursor
      }
    },

```
`gc`
```
    -- smart_rename = {
      -- enable = true,
      -- keymaps = {
        -- smart_rename = "grr"          -- mapping to rename reference under cursor
      -- }
    -- },
```
(sidebar, just noticed that toggling visually selected blocks doesn't remove the visual selection when you `gc` it 🤯, never knew i really wanted this feature!)

Desired behavior:
```
   -- smart_rename = {
   --   enable = true,
   --   keymaps = {
   --     smart_rename = "grr"          -- mapping to rename reference under cursor
   --   }
   -- },
```

**Comment by b3nj5m1n** [comment] 2021-02-03 14:47
Duplicate of #5, I implemented this literally 40 minutes ago with #12 :)

If you update the plugin, it should be set as default, but here is how you would configure it:
```lua
require('kommentary.config').configure_language("default", {
    use_consistent_indentation = true,
})
```

**Closed by b3nj5m1n** 2021-02-03 14:47 UTC

**Comment by DanCardin** [comment] 2021-02-03 14:55
Oh dang! I ignored the closed issues and didn't notice it in the readme, sorry!

Updated, set, and it works great, thanks!

**Comment by b3nj5m1n** [comment] 2021-02-03 14:56
Absolutely no problem @DanCardin, it's great to hear that it works, I was a bit worried about bugs since this was quite a big change, so if you encounter any problems at all be sure to let me know!
